import { useState } from 'react';
import AIPromptForm from '@/components/AIPromptForm';
import { Card, CardContent } from '@/components/ui/card';
import { Sparkles } from 'lucide-react';
const AIScreen = () => {
  return <div className="min-h-[calc(100vh-6rem)] px-4 py-6">
      <div className="text-center mb-8">
        <h1 className="text-3xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-binaural-purple to-binaural-blue flex items-center justify-center gap-2">
          <Sparkles className="text-binaural-purple" size={24} />
          <span>AI Mode</span>
        </h1>
        <p className="text-muted-foreground mt-2">
          Get personalized binaural beat mixes generated by AI
        </p>
      </div>
      
      <Card className="bg-secondary/10 border-secondary/30 shadow-lg mb-6">
        <CardContent className="p-4">
          <AIPromptForm />
        </CardContent>
      </Card>
      
      
    </div>;
};
export default AIScreen;